### ISSUE TITLE
SDS biocache-store functionality broken since February 24

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/data-management#300]
The Individual Sightings Re-import job on jenkins has been silently failing since 24 February, with a very large log file each time, around 500MB.

**Comment by ansell** [comment]
The stacktrace seems to indicate invalid XML, possibly related to the SDS service:

```
2017-02-24 18:09:19,477 ERROR: [RecordProcessor] - Error processing record: dr364|urn:lsid:cs.ala.org.au:Record:9867, Error on line 28: The element type "meta" must be terminated by the matching end-tag "</meta>".
org.jdom.input.JDOMParseException: Error on line 28: The element type "meta" must be terminated by the matching end-tag "</meta>".
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:468)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:770)
	at au.org.ala.sds.dao.SensitiveSpeciesXmlDao.getAll(SensitiveSpeciesXmlDao.java:45)
	at au.org.ala.sds.model.SensitiveTaxonStore.<init>(SensitiveTaxonStore.java:51)
	at au.org.ala.sds.SensitiveSpeciesFinderFactory.getStoreFromUrl(SensitiveSpeciesFinderFactory.java:103)
	at au.org.ala.sds.SensitiveSpeciesFinderFactory.getSensitiveSpeciesFinder(SensitiveSpeciesFinderFactory.java:61)
	at au.org.ala.sds.SensitiveSpeciesFinderFactory.getSensitiveSpeciesFinder(SensitiveSpeciesFinderFactory.java:44)
	at au.org.ala.biocache.Config$.sdsFinder$lzycompute(Config.scala:65)
	at au.org.ala.biocache.Config$.sdsFinder(Config.scala:62)
	at au.org.ala.biocache.processor.LocationProcessor.processSensitivity(LocationProcessor.scala:1034)
	at au.org.ala.biocache.processor.LocationProcessor.process(LocationProcessor.scala:90)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:101)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:98)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at au.org.ala.biocache.processor.Processors$.foreach(Processors.scala:12)
	at au.org.ala.biocache.processor.RecordProcessor.processRecord(RecordProcessor.scala:98)
	at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1$$anonfun$applyOrElse$1.apply(ProcessRecords.scala:337)
	at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1$$anonfun$applyOrElse$1.apply(ProcessRecords.scala:331)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1.applyOrElse(ProcessRecords.scala:331)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at scala.actors.ReactorTask.run(ReactorTask.scala:31)
	at scala.actors.ReactorTask.compute(ReactorTask.scala:63)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.xml.sax.SAXParseException; lineNumber: 28; columnNumber: 3; The element type "meta" must be terminated by the matching end-tag "</meta>".
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	... 33 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 28; columnNumber: 3; The element type "meta" must be terminated by the matching end-tag "</meta>".
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:453)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:770)
	at au.org.ala.sds.dao.SensitiveSpeciesXmlDao.getAll(SensitiveSpeciesXmlDao.java:45)
	at au.org.ala.sds.model.SensitiveTaxonStore.<init>(SensitiveTaxonStore.java:51)
	at au.org.ala.sds.SensitiveSpeciesFinderFactory.getStoreFromUrl(SensitiveSpeciesFinderFactory.java:103)
	at au.org.ala.sds.SensitiveSpeciesFinderFactory.getSensitiveSpeciesFinder(SensitiveSpeciesFinderFactory.java:61)
	at au.org.ala.sds.SensitiveSpeciesFinderFactory.getSensitiveSpeciesFinder(SensitiveSpeciesFinderFactory.java:44)
	at au.org.ala.biocache.Config$.sdsFinder$lzycompute(Config.scala:65)
	at au.org.ala.biocache.Config$.sdsFinder(Config.scala:62)
	at au.org.ala.biocache.processor.LocationProcessor.processSensitivity(LocationProcessor.scala:1034)
	at au.org.ala.biocache.processor.LocationProcessor.process(LocationProcessor.scala:90)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:101)
	at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:98)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
	at au.org.ala.biocache.processor.Processors$.foreach(Processors.scala:12)
	at au.org.ala.biocache.processor.RecordProcessor.processRecord(RecordProcessor.scala:98)
	at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1$$anonfun$applyOrElse$1.apply(ProcessRecords.scala:337)
	at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1$$anonfun$applyOrElse$1.apply(ProcessRecords.scala:331)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1.applyOrElse(ProcessRecords.scala:331)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at scala.actors.ReactorTask.run(ReactorTask.scala:31)
	at scala.actors.ReactorTask.compute(ReactorTask.scala:63)
	at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ansell** [comment]
This is also affecting Spot our species, so it isn't specific to the individual sightings, retargeted issue to match.

**Comment by adam-collins** [comment]
After updates and a redeploy this record can now be processed.
``biocache process -s "dr364|urn:lsid:cs.ala.org.au:Record:9867" -e "dr364|urn:lsid:cs.ala.org.au:Record:9867"``

**Comment by ansell** [comment]
Thanks, the errors are not occurring anymore
