### ISSUE TITLE
GBIF Audit : dr690 eml.xml not generated by collectory, breaking export

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/data-management#307]
GBIF identified that although the directory exists for dr690, there is no dr690 DWCA file. Cause is that it does not have its eml.xml generated correctly by the collectory, returning ``HTTP 404`` for ``http://collections.ala.org.au/ws/eml/dr690`` and propagating this as a java FileNotFoundException during the export job. 

```
2017-06-15 04:41:43,578 INFO : [DwCACreator] - Creating archive for dr690
java.io.FileNotFoundException: http://collections.ala.org.au/ws/eml/dr690
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.URL.openStream(URL.java:1041)
	at scala.io.Source$.fromURL(Source.scala:140)
	at scala.io.Source$.fromURL(Source.scala:130)
	at au.org.ala.biocache.export.DwCACreator.addEML(DwCACreator.scala:127)
	at au.org.ala.biocache.export.DwCACreator.create(DwCACreator.scala:112)
	at au.org.ala.biocache.export.DwCACreator$$anonfun$main$1.apply(DwCACreator.scala:44)
	at au.org.ala.biocache.export.DwCACreator$$anonfun$main$1.apply(DwCACreator.scala:44)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.export.DwCACreator$.main(DwCACreator.scala:44)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:134)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
```

This prevents the export from occurring. I deleted the directory manually to see if it is recreated automatically next time.

**Comment by ansell** [comment]
This was an early load from the Tasmanian Natural Values Atlas, and can be removed as the contents are now in http://collections.ala.org.au/public/show/dr710
