### ISSUE TITLE
Load NZVH

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/data-management#426]
load NZVH data from IPT

**Comment by ansell** [comment]
Download using two CURL commands is:

```
#!/bin/bash

set +e
set +x

curl -o 'login-result.html' 'http://ipt.landcareresearch.co.nz/login.do' -XPOST -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Referer: http://ipt.landcareresearch.co.nz/login' -H 'Host: ipt.landcareresearch.co.nz' -H 'User-Agent: Mozilla/5.0 (AtlasOfLivingAustralia https://www.ala.org.au/)' -d 'email=[REDACTED]@[REDACTED]' -d 'password=[REDACTED]' -d 'portal.login=login' --cookie-jar ~/ipt-cookies.txt

curl -o 'nzvh.zip' 'http://ipt.landcareresearch.co.nz/archive.do?r=nzvh' -H 'Referer: http://ipt.landcareresearch.co.nz/resource?r=nzvh' -H 'Host: ipt.landcareresearch.co.nz' -H 'User-Agent: Mozilla/5.0 (AtlasOfLivingAustralia https://www.ala.org.au/)' --cookie ~/ipt-cookies.txt
```

Will create a job on `ala-dury` with those two commands and make it trigger a load on `aws-scjenkins`

**Comment by ansell** [comment]
Data load failed with an exception about an incorrectly cased Cassandra column name:

```
aws-bstore-1b 2018-11-27 13:30:03,341 ERROR: [Cassandra3PersistenceManager] - Incorrect column case. requested: 'accessrights', actual: 'accessRights', query: INSERT INTO occ (rowkey,"collectionID","geodeticDatum","stateProvince","catalogNumber","institutionCode","collectionCode","defaultValuesUsed","taxonRank","modified","country","basisOfRecord","taxonomicallyKosher","decimalLongitude","genus","verbatimEventDate","scientificName","family","lastModifiedTime","occurrenceID","decimalLatitude","typeStatus","eventDate","accessrights","taxonID","recordedBy","firstLoaded","miscProperties","dataResourceUid","locationDetermined","geospatiallyKosher") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
aws-bstore-1b 2018-11-27 13:30:03,342 ERROR: [Cassandra3PersistenceManager] - Undefined column name accessrights
com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name accessrights
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:104)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.getPreparedStmt(Cassandra3PersistenceManager.scala:89)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.createPutStatement(Cassandra3PersistenceManager.scala:483)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.put(Cassandra3PersistenceManager.scala:413)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$putBatch$1.apply(Cassandra3PersistenceManager.scala:401)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$putBatch$1.apply(Cassandra3PersistenceManager.scala:395)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.putBatch(Cassandra3PersistenceManager.scala:395)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl.addRawOccurrenceBatch(OccurrenceDAOImpl.scala:578)
	at au.org.ala.biocache.load.DwCALoader$$anonfun$loadArchive$1.apply(DwCALoader.scala:286)
	at au.org.ala.biocache.load.DwCALoader$$anonfun$loadArchive$1.apply(DwCALoader.scala:228)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.load.DwCALoader.loadArchive(DwCALoader.scala:228)
	at au.org.ala.biocache.load.DwCALoader$$anonfun$load$1.apply(DwCALoader.scala:126)
	at au.org.ala.biocache.load.DwCALoader$$anonfun$load$1.apply(DwCALoader.scala:117)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.load.DwCALoader.load(DwCALoader.scala:117)
	at au.org.ala.biocache.load.Loader.load(Loader.scala:209)
	at au.org.ala.biocache.load.Loader$$anonfun$main$4.apply(Loader.scala:96)
	at au.org.ala.biocache.load.Loader$$anonfun$main$4.apply(Loader.scala:96)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.load.Loader$.main(Loader.scala:95)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:133)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name accessrights
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:147)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:111)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:992)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
aws-bstore-1b 2018-11-27 13:30:03,344 ERROR: [Cassandra3PersistenceManager] - Problem persisting the following to occ - Undefined column name accessrights
com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name accessrights
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:104)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.getPreparedStmt(Cassandra3PersistenceManager.scala:89)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.createPutStatement(Cassandra3PersistenceManager.scala:483)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.put(Cassandra3PersistenceManager.scala:413)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$putBatch$1.apply(Cassandra3PersistenceManager.scala:401)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$putBatch$1.apply(Cassandra3PersistenceManager.scala:395)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174)
	at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.putBatch(Cassandra3PersistenceManager.scala:395)
	at au.org.ala.biocache.dao.OccurrenceDAOImpl.addRawOccurrenceBatch(OccurrenceDAOImpl.scala:578)
	at au.org.ala.biocache.load.DwCALoader$$anonfun$loadArchive$1.apply(DwCALoader.scala:286)
	at au.org.ala.biocache.load.DwCALoader$$anonfun$loadArchive$1.apply(DwCALoader.scala:228)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.load.DwCALoader.loadArchive(DwCALoader.scala:228)
	at au.org.ala.biocache.load.DwCALoader$$anonfun$load$1.apply(DwCALoader.scala:126)
	at au.org.ala.biocache.load.DwCALoader$$anonfun$load$1.apply(DwCALoader.scala:117)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at au.org.ala.biocache.load.DwCALoader.load(DwCALoader.scala:117)
	at au.org.ala.biocache.load.Loader.load(Loader.scala:209)
	at au.org.ala.biocache.load.Loader$$anonfun$main$4.apply(Loader.scala:96)
	at au.org.ala.biocache.load.Loader$$anonfun$main$4.apply(Loader.scala:96)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at au.org.ala.biocache.load.Loader$.main(Loader.scala:95)
	at au.org.ala.biocache.cmd.CMD2$.main(CMD2.scala:133)
	at au.org.ala.biocache.cmd.CMD2.main(CMD2.scala)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name accessrights
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:147)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:111)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:992)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ansell** [comment]
Opened an issue on biocache-store to track the incorrect cased field, after verifying that the Darwin Core Archive contains the correct casing and IRI: https://github.com/AtlasOfLivingAustralia/biocache-store/issues/300

**Comment by M-Nicholls** [comment]
Mahmoud put a fix in and data is loaded

**Comment by ansell** [comment]
The Jenkins job for the load reported 930742 records, but biocache only shows 930211 records. The reindex occurred just before the load in this case, so reopening and will check again after the next reindex to see if it synchronises.

**Comment by ansell** [comment]
There are 45 records in dr2153 that were not present in the latest load, will delete these: 

https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr2153&fq=-last_load_date%3A[2019-01-06T01%3A33%3A51Z+TO+*]

Removing those 45 records from the current 930774 records should leave 930729 records, which is still not equal to the reported load count of 930742 records

**Comment by ansell** [comment]
Waiting on stabilisation of to the `Delete Records by Query` jenkins job before running this. Leaving this in `Waiting for...` for now

**Comment by ansell** [comment]
Delete run on the 45 records above
