### ISSUE TITLE
2023-03-01 Solr index FAILURE!

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/data-management#857]

**Comment by sadeghim** [comment]
```
WARNING: SEVERE- The new index doesn't have any record for dataResourceUid="dr17780" .
```

**Comment by charvolant** [comment]
Caused by an attempt to load a new versioon yesterday. The DR index construction is falling over for no obvious reason.

**Comment by charvolant** [comment]
111
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at org.gbif.pipelines.core.interpreters.Interpretation$Handler.get(Interpretation.java:132)
	at au.org.ala.pipelines.transforms.LocationTransform.convert(LocationTransform.java:180)
	at au.org.ala.pipelines.transforms.LocationTransform.convert(LocationTransform.java:32)
	at org.gbif.pipelines.transforms.Transform.processElement(Transform.java:156)
	at org.gbif.pipelines.transforms.Transform.processElement(Transform.java:152)
```

**Comment by javier-molina** [comment]
From Doug

> dr17780 has loaded successfully. The culprit was a couple of completely blank records.
